### PR TITLE
Add Laravel 6 compatabilitiy

### PR DESCRIPTION
**Pull request by RSpeekenbrink**
Adds Laravel 6 compatability and replaces deprecated helper functions.

### CODE REVIEW

**Comment by bonroyage** [comment]
Thanks, the only issue I see with this is that the `Arr` class doesn't exist yet in illuminate/support [4.0](https://github.com/illuminate/support/tree/4.0) and [4.1](https://github.com/illuminate/support/tree/4.1). It was introduced in [4.2](https://github.com/illuminate/support/tree/4.2). 

Two solutions:
1. Set the minimum version to 4.2
2. Set the minimum version to  5.0 and also get rid of the check in the service provider
3. Add those helpers in the package itself which I don't see as a solution because 4.1 was released in December 2013, almost 6 years ago.

**Comment by RSpeekenbrink** [comment]
I guess option 2 is the best since Laravel 4 is deprecated a long time ago and not really supported anymore.

**Comment by RSpeekenbrink** [comment]
@bonroyage agree with option 2?

**Comment by bonroyage** [comment]
Ah sorry, yes. I'll merge this and tag it as version 3.1.

**Comment by RSpeekenbrink** [comment]
Thanks, could you also refresh packagist so we can use 3.1? :smiley:

**Comment by bonroyage** [comment]
Just updated it.

**Pull request merged**
